#
# prawns' basic unit is PostScript-Point
# 72 points per inch
#

Avery8660:
    paper_size: LETTER
    top_margin: 36
    bottom_margin: 36
    left_margin: 15.822
    right_margin: 15.822
    columns: 3
    rows: 10
    column_gutter: 15
    row_gutter: 0

